"""T50M Pro / Katasymbol Windows printer application."""

__version__ = "0.1.0"

VID = 0x1820
PID = 0x207F
DPI = 203
DOTS_PER_MM = 8
PRINTHEAD_WIDTH_MM = 48
PRINTHEAD_WIDTH_DOTS = PRINTHEAD_WIDTH_MM * DOTS_PER_MM  # 384
PRINTHEAD_BYTES_PER_LINE = PRINTHEAD_WIDTH_DOTS // 8  # 48
DEFAULT_DENSITY = 3
DEFAULT_MARGIN_DOTS = 8
DEFAULT_LABEL_HEIGHT_MM = 30
HID_REPORT_SIZE = 64
